---
alexakarpov:
  hosts:
    www.alexakarpov.xyz:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /Users/akarpov/keypairs/alexakarpov.xyz/ak_kp_1.pem

staging:
  hosts:
    ec2-35-183-62-66.ca-central-1.compute.amazonaws.com:
  vars:
    ansible_user: ubuntu
    become_user: root
    ansible_ssh_private_key_file: ./secrets/puj_07_2018_ak.pem"
