---
- hosts: staging
  become: true
  tasks:
    - name: Install pip
      apt: name=python-pip state=present
    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present
    - name: Install pipenv
      pip:
        name: pipenv
        state: present
    - name: Install requirements
      copy:
        src: testing-requirements.txt
        dest: /home/lucy/puj/requirements.txt
        owner: lucy
        group: lucy
