---
- hosts: "{{ puj_hosts | default('alexakarpov') }}"
  vars_files:
    - vars.yml
  become: true
  tasks:
    - name: Install akarpov
      user:
        name: akarpov
        groups: admin
        shell: /usr/bin/zsh
        createhome: yes
    - name: Deploy akarpov's public key
      authorized_key:
        user: akarpov
        state: present
        key: "{{ lookup('file', 'public/akarpov/personal.pub')}}"
    - name: Install martin
      user:
        name: martin
        groups: admin
        createhome: yes
    - name: Deploy martin's public key
      authorized_key:
        user: martin
        state: present
        key: "{{ lookup('file', 'public/martin/personal.pub')}}"
    - name: Install a testing user
      user:
        name: lucy
        createhome: yes
        groups: www-data
        comment: Lucy the Organizer
