---
- hosts: staging
  vars_files:
    - vars.yml
  become: true
  tasks:
    - name: Deploy the repo
      become: yes
      become_user: ubuntu
      git:
        repo: 'git@bitbucket.org:teampuj/payupjack.git'
        version: "{{ deployment_version }}"
        dest: "{{ deployment_dest }}"
        depth: 1
    - name: Ensure log dir exists
      file:
        name: /opt/PUJ/logs
        state: directory
        owner: ubuntu
        group: admin
    - name: restart Apache
      service:
        name: apache2
        state: restarted
        enabled: yes
