---
- hosts: staging
  vars_files:
    - vars.yml
  become: true
  tasks:
    - name: Ensure dest folder exists
      file:
        path: "{{ deployment_dest }}"
        state: directory
        owner: ubuntu
        group: admin
        mode: 0755
    - name: Fake it till you make it
      shell: "cp -r {{deployment_src}}/* {{deployment_dest}}"
